[package]
name = "boop"
version = "0.1.0"
authors = ["viri <hi@viri.moe>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
